name: storybook
on: push
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: npm
    - uses: actions/configure-pages@v5
    - run: npm install
    - run: npm run build:pages
    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./storybook-static
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
    