name: wdio
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Chromium
      run: sudo apt-get install chromium-browser
    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: npm
    - run: npm install
    - run: npm run test:headless
